function f_L = improveFits(Al,Fl,f_L,f_U,num_iter)
%% Corrects the fits generated by generateFits
x = (0:1:255)';

[~, ind] = sort(Al);

temp1 = f_U(x);
for i = 1:num_iter
    f = Fl{ind(i)};
    temp2 = f(x);
    if( ~sum(temp2 > temp1) )
        f_L = f;
        break;
    end
end

end
 